#
#     ______            _____                        __  _
#    / ____/___  ____  / __(_)___ ___  ___________ _/ /_(_)___  ____
#   / /   / __ \/ __ \/ /_/ / __ `/ / / / ___/ __ `/ __/ / __ \/ __ \
#  / /___/ /_/ / / / / __/ / /_/ / /_/ / /  / /_/ / /_/ / /_/ / / / /
#  \____/\____/_/ /_/_/ /_/\__, /\__,_/_/   \__,_/\__/_/\____/_/ /_/
#                         /____/
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  packages:
    active_player: !include packages/active_player.yaml
    hass_sidebar_helpers: !include packages/hassio/hass_sidebar_helpers.yaml
    energy_estimated: !include packages/energy_estimated.yaml
    sala_tv_controls: !include packages/sala_tv_controls.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: storage
  dashboards:
    ngocjohn-main:
      mode: yaml
      title: Ngocjohn Main
      icon: mdi:home-automation
      show_in_sidebar: true
      filename: dashboards/ui-lovelace-main.yaml
    
    # --- NOVO DASHBOARD DE TESTE ---
    homekitesq-teste:
      mode: yaml
      title: Teste HomeKit
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      filename: lovelace-homekitesq.yaml
